import './styles/vars.css'
import './styles/base.css'
import './styles/icons.css'
import './styles/utils.css'
import './styles/components/custom-block.css'
import './styles/components/vp-code.css'
import './styles/components/vp-code-group.css'
import './styles/components/vp-doc.css'
import './styles/components/vp-sponsor.css'
import './styles/components/NotFound.css'
import './styles/components/VPBackdrop.css'
import './styles/components/VPBadge.css'
import './styles/components/VPButton.css'
import './styles/components/VPCarbonAds.css'
import './styles/components/VPContent.css'
import './styles/components/VPDoc.css'
import './styles/components/VPDocAside.css'
import './styles/components/VPDocAsideOutline.css'
import './styles/components/VPDocFooter.css'
import './styles/components/VPDocFooterLastUpdated.css'
import './styles/components/VPDocOutlineItem.css'
import './styles/components/VPFeature.css'
import './styles/components/VPFeatures.css'
import './styles/components/VPFlyout.css'
import './styles/components/VPFooter.css'
import './styles/components/VPHero.css'
import './styles/components/VPHome.css'
import './styles/components/VPHomeContent.css'
import './styles/components/VPHomeSponsors.css'
import './styles/components/VPImage.css'
import './styles/components/VPLocalNav.css'
import './styles/components/VPLocalNavOutlineDropdown.css'
import './styles/components/VPLocalSearchBox.css'
import './styles/components/VPMenu.css'
import './styles/components/VPMenuGroup.css'
import './styles/components/VPMenuLink.css'
import './styles/components/VPNav.css'
import './styles/components/VPNavBar.css'
import './styles/components/VPNavBarAppearance.css'
import './styles/components/VPNavBarAskAiButton.css'
import './styles/components/VPNavBarExtra.css'
import './styles/components/VPNavBarHamburger.css'
import './styles/components/VPNavBarMenu.css'
import './styles/components/VPNavBarMenuLink.css'
import './styles/components/VPNavBarSearch.css'
import './styles/components/VPNavBarSearchButton.css'
import './styles/components/VPNavBarSocialLinks.css'
import './styles/components/VPNavBarTitle.css'
import './styles/components/VPNavBarTranslations.css'
import './styles/components/VPNavScreen.css'
import './styles/components/VPNavScreenAppearance.css'
import './styles/components/VPNavScreenMenuGroup.css'
import './styles/components/VPNavScreenMenuGroupLink.css'
import './styles/components/VPNavScreenMenuGroupSection.css'
import './styles/components/VPNavScreenMenuLink.css'
import './styles/components/VPNavScreenTranslations.css'
import './styles/components/VPSidebar.css'
import './styles/components/VPSidebarGroup.css'
import './styles/components/VPSidebarItem.css'
import './styles/components/VPSkipLink.css'
import './styles/components/VPSocialLink.css'
import './styles/components/VPSocialLinks.css'
import './styles/components/VPSwitch.css'
import './styles/components/VPSwitchAppearance.css'
import './styles/components/VPTeamMembers.css'
import './styles/components/VPTeamMembersItem.css'
import './styles/components/VPTeamPage.css'
import './styles/components/VPTeamPageSection.css'
import './styles/components/VPTeamPageTitle.css'

import type { Theme } from 'vitepress'
import VPBadge from './components/VPBadge.vue'
import Layout from './Layout.vue'

export { default as VPBadge } from './components/VPBadge.vue'
export { default as VPButton } from './components/VPButton.vue'
export { default as VPDocAsideSponsors } from './components/VPDocAsideSponsors.vue'
export { default as VPFeatures } from './components/VPFeatures.vue'
export { default as VPHomeContent } from './components/VPHomeContent.vue'
export { default as VPHomeFeatures } from './components/VPHomeFeatures.vue'
export { default as VPHomeHero } from './components/VPHomeHero.vue'
export { default as VPHomeSponsors } from './components/VPHomeSponsors.vue'
export { default as VPImage } from './components/VPImage.vue'
export { default as VPLink } from './components/VPLink.vue'
export { default as VPNavBarSearch } from './components/VPNavBarSearch.vue'
export { default as VPSocialLink } from './components/VPSocialLink.vue'
export { default as VPSocialLinks } from './components/VPSocialLinks.vue'
export { default as VPSponsors } from './components/VPSponsors.vue'
export { default as VPTeamMembers } from './components/VPTeamMembers.vue'
export { default as VPTeamPage } from './components/VPTeamPage.vue'
export { default as VPTeamPageSection } from './components/VPTeamPageSection.vue'
export { default as VPTeamPageTitle } from './components/VPTeamPageTitle.vue'

export { useLayout } from './composables/layout'

const theme: Theme = {
  Layout,
  enhanceApp: ({ app }) => {
    app.component('Badge', VPBadge)
  }
}

export default theme
