import './styles/vars.css'
import './styles/base.css'
import './styles/icons.css'
import './styles/utils.css'
import './styles/components/custom-block.css'
import './styles/components/vp-code.css'
import './styles/components/vp-code-group.css'
import './styles/components/vp-doc.css'
import './styles/components/vp-sponsor.css'
import './styles/components/vp-badge.css'
import './styles/components/vp-button.css'
import './styles/components/vp-image.css'
import './styles/components/vp-skip-link.css'
import './styles/components/vp-menu.css'
import './styles/components/vp-switch.css'
import './styles/components/vp-flyout.css'
import './styles/components/vp-nav.css'
import './styles/components/vp-nav-appearance.css'
import './styles/components/vp-social-links.css'
import './styles/components/vp-sponsors.css'
import './styles/components/vp-team.css'
import './styles/components/vp-local-search.css'
import './styles/components/vp-nav-screen.css'
import './styles/components/vp-sidebar.css'
import './styles/components/vp-local-nav.css'
import './styles/components/vp-footer.css'
import './styles/components/vp-backdrop.css'
import './styles/components/vp-home.css'
import './styles/components/vp-page.css'

import type { Theme } from 'vitepress'
import { Layout } from './Layout'

export { VPBadge } from './components/VPBadge'
export { VPButton } from './components/VPButton'
export { VPDocAsideSponsors } from './components/VPDocAsideSponsors'
export { VPFeatures } from './components/VPFeatures'
export { VPHomeContent } from './components/VPHomeContent'
export { VPHomeFeatures } from './components/VPHomeFeatures'
export { VPHomeHero } from './components/VPHomeHero'
export { VPHomeSponsors } from './components/VPHomeSponsors'
export { VPImage } from './components/VPImage'
export { VPLink } from './components/VPLink'
export { VPNavBarSearch } from './components/VPNavBarSearch'
export { VPSocialLink } from './components/VPSocialLink'
export { VPSocialLinks } from './components/VPSocialLinks'
export { VPSponsors } from './components/VPSponsors'
export { VPTeamMembers } from './components/VPTeamMembers'
export { VPTeamPage } from './components/VPTeamPage'
export { VPTeamPageSection } from './components/VPTeamPageSection'
export { VPTeamPageTitle } from './components/VPTeamPageTitle'

export { useLayout } from './composables/layout'

const theme: Theme = {
  Layout
  // enhanceApp 的全局组件注册（app.component）随 Vue 移除；
  // md 内 <Badge> 等组件标签的解析通道在 C 阶段实现
}

export default theme
