import './styles/vars.css'
import './styles/base.css'
import './styles/icons.css'
import './styles/utils.css'
import './styles/components/custom-block.css'
import './styles/components/vp-code.css'
import './styles/components/vp-code-group.css'
import './styles/components/vp-doc.css'
import './styles/components/vp-sponsor.css'
import './styles/components/VPBackdrop.css'
import './styles/components/VPBadge.css'
import './styles/components/VPButton.css'
import './styles/components/VPCarbonAds.css'
import './styles/components/VPContent.css'
import './styles/components/VPDoc.css'
import './styles/components/VPDocAside.css'
import './styles/components/VPDocAsideOutline.css'
import './styles/components/VPDocFooter.css'
import './styles/components/VPDocFooterLastUpdated.css'
import './styles/components/VPDocOutlineItem.css'
import './styles/components/VPFeature.css'
import './styles/components/VPFeatures.css'
import './styles/components/VPFlyout.css'
import './styles/components/VPFooter.css'
import './styles/components/VPHero.css'
import './styles/components/VPHome.css'
import './styles/components/VPHomeContent.css'
import './styles/components/VPHomeSponsors.css'
import './styles/components/VPImage.css'
import './styles/components/VPLocalNav.css'
import './styles/components/VPLocalNavOutlineDropdown.css'
import './styles/components/VPLocalSearchBox.css'
import './styles/components/VPMenu.css'
import './styles/components/VPMenuGroup.css'
import './styles/components/VPMenuLink.css'
import './styles/components/VPNav.css'
import './styles/components/VPNavBar.css'
import './styles/components/VPNavBarAppearance.css'
import './styles/components/VPNavBarAskAiButton.css'
import './styles/components/VPNavBarExtra.css'
import './styles/components/VPNavBarHamburger.css'
import './styles/components/VPNavBarMenu.css'
import './styles/components/VPNavBarMenuLink.css'
import './styles/components/VPNavBarSearch.css'
import './styles/components/VPNavBarSearchButton.css'
import './styles/components/VPNavBarSocialLinks.css'
import './styles/components/VPNavBarTitle.css'
import './styles/components/VPNavBarTranslations.css'
import './styles/components/VPNavScreen.css'
import './styles/components/VPNavScreenAppearance.css'
import './styles/components/VPNavScreenMenuGroup.css'
import './styles/components/VPNavScreenMenuGroupLink.css'
import './styles/components/VPNavScreenMenuGroupSection.css'
import './styles/components/VPNavScreenMenuLink.css'
import './styles/components/VPNavScreenTranslations.css'
import './styles/components/VPSidebar.css'
import './styles/components/VPSidebarGroup.css'
import './styles/components/VPSidebarItem.css'
import './styles/components/VPSkipLink.css'
import './styles/components/VPSocialLink.css'
import './styles/components/VPSocialLinks.css'
import './styles/components/VPSwitch.css'
import './styles/components/VPSwitchAppearance.css'
import './styles/components/VPTeamMembers.css'
import './styles/components/VPTeamMembersItem.css'
import './styles/components/VPTeamPage.css'
import './styles/components/VPTeamPageSection.css'
import './styles/components/VPTeamPageTitle.css'
import './styles/components/Layout.css'
import './styles/components/NotFound.css'

import type { Theme } from 'actpress'
import { Layout } from './Layout'

export { VPBadge } from './components/VPBadge'
export { VPButton } from './components/VPButton'
export { VPDocAsideSponsors } from './components/VPDocAsideSponsors'
export { VPFeatures } from './components/VPFeatures'
export { VPHomeContent } from './components/VPHomeContent'
export { VPHomeFeatures } from './components/VPHomeFeatures'
export { VPHomeHero } from './components/VPHomeHero'
export { VPHomeSponsors } from './components/VPHomeSponsors'
export { VPImage } from './components/VPImage'
export { VPLink } from './components/VPLink'
export { VPNavBarSearch } from './components/VPNavBarSearch'
export { VPSocialLink } from './components/VPSocialLink'
export { VPSocialLinks } from './components/VPSocialLinks'
export { VPSponsors } from './components/VPSponsors'
export { VPTeamMembers } from './components/VPTeamMembers'
export { VPTeamPage } from './components/VPTeamPage'
export { VPTeamPageSection } from './components/VPTeamPageSection'
export { VPTeamPageTitle } from './components/VPTeamPageTitle'

export { useLayout } from './composables/layout'

const theme: Theme = {
  Layout
  // enhanceApp 的全局组件注册（app.component）随 Vue 移除；
  // md 内 <Badge> 等组件标签的解析通道在 C 阶段实现
}

export default theme
